enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"App.css",
	"LocalStore.js",
	"MapControl.js",
	"RoadImgItem.js",
	"CurrentLocation.js",
	"CameraData.js",
	"Privacy.js",
	"About.js",
	"CameraView.js",
	"SettingsView.js",
	"MainPanel.js",
	"ListRoadways.js",
	"App.js"
);
